sudo: required
services:
  - docker

# Before we run the tests
before_install:
  - docker build -t neeraj76/frontend -f Dockerfile.dev .

# All commands to run test suite
script:
  - docker run -e CI=true USERNAME/docker-react npm run test
