sudo: required
services:
  - docker

# Before we run the tests
before_install:
  - docker build -t neeraj76/frontend -f Dockerfile.dev .

# All commands to run test suite
script:
  - docker run -e CI=true neeraj76/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket: "elasticbeanstalk-us-east-2-764022628003"
  bucket_path: "docker-frontend"
  on:
    branch: master